default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  sslmode: <%= ENV.fetch("DB_SSLMODE", "require") %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
